#! /bin/sh

#sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor -d I II III IV V
#bspc monitor HDMI-2 -d VI VIII IX X

bspc config click_to_focus button1

bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#36b7cf"
bspc config presel_feedback_color "#fbf1c7"

bspc config top_padding		10
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#Window states for certain apps when opened
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Code desktop='^3'
#bspc rule -a Firefox desktop='^1' state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Electron state=floating
bspc rule -a charles state=floating
bspc rule -a 'com-xk72-charles-gui-MainWithClassLoader' state=floating


#Open the following when startx is activated
panel &
#urxvt &
code &
firefox --private-window &
